Tictactoe
BenKurrek/grid-like-game-optimizations pull request #9
Opened 2023-11-28 19:43 UTC by minqianlu

2023-11-28 23:57 UTC, BenKurrek requested changes

2023-11-28 23:57 UTC, BenKurrek commented on main.py
> +        if game_name == "tictactoe":
Fix please

2023-11-28 23:57 UTC, BenKurrek commented on main.py
> +        if game_name == "tictactoe":
fix please

2023-11-28 23:57 UTC, BenKurrek commented on src/game/tictactoe/pawn.py
> +class PawnEvaluator:
remove this file please

2023-11-28 23:57 UTC, BenKurrek commented on src/game/tictactoe/ttt_game.py
> +        self.moves_and_scores = sorted(self.moves_and_scores, key=lambda x: x[1], reverse=True)
you didn't change this to a proper data structure... this is innefficient. Normally I would say change it but tic tac toe is not very intensive so it's not that big a deal.

2023-11-28 23:57 UTC, BenKurrek commented on src/optimization/genetic_algorithm.py
> +            print(board_data)
remove

2023-11-28 23:57 UTC, BenKurrek commented on src/optimization/genetic_algorithm.py
> +            # self.game = Othello( )  # Replace with actual Othello initialization
remove

2023-11-28 23:57 UTC, BenKurrek commented on src/optimization/genetic_algorithm.py
> +            if not (generation + 1) % 10:
remove logs

2023-11-28 23:57 UTC, BenKurrek commented on src/utility/chess_extraction.py
> +    myEngine = engine.SimpleEngine.popen_uci("./stockfish")
revert please

2023-11-29 00:04 UTC, zdefranc commented on config.ini
>  ; chess, go, othello
Change go to "tictactoe"

2023-11-29 00:04 UTC, zdefranc commented on main.py
> +    print(f"{Fore.MAGENTA}~~~~~~~~~~~~~~~~~~~~   STARTING ALGORITHM   ~~~~~~~~~~~~~~~~~~~~{Style.RESET_ALL}")
Remove

2023-11-29 00:04 UTC, zdefranc commented on main.py
> +            generations = 20
Generations should be set individually remove if statement

2023-11-29 00:04 UTC, zdefranc commented on main.py
> +        if game_name == "tictactoe":
Remove tictactoe only if statement

2023-11-29 00:04 UTC, zdefranc commented on src/game/tictactoe/ttt_game.py
> +        rank = 1
Best move should be 0 according to every other game convention

2023-11-29 00:04 UTC, zdefranc commented on src/optimization/genetic_algorithm.py
> +                print(f"{Fore.CYAN}~~~~~~~~~~~~~~~~~~~~   GENERATION: {generation + 1}   ~~~~~~~~~~~~~~~~~~~~{Style.RESET_ALL}")
Should this be here?

2023-11-29 00:04 UTC, zdefranc commented on src/optimization/genetic_algorithm.py
> +            if not (generation + 1) % 10:
Is this necessary?

2023-11-29 00:04 UTC, zdefranc commented on src/optimization/genetic_algorithm.py
> +            if not (generation + 1) % 10:
Is this necessary?

2023-11-29 00:48 UTC, merged